In [13]:
import pandas as pd

df = pd.read_csv("./insurance_dataset.csv")

df = df.sample(13330)

df.to_csv("./df_reduced.csv", sep=",", index=False)

In [21]:
import pandas as pd

df = pd.read_csv("./df_reduced.csv")

df.dropna(inplace=True)

for i in df.index:
    if 18 <= df.loc[i, "age"] < 26:
        df.loc[i, "age2"] = "18-26"
    elif 26 <= df.loc[i, "age"] < 41:
        df.loc[i, "age2"] = "26-41"
    elif 41 <= df.loc[i, "age"] < 56:
        df.loc[i, "age2"] = "41-56"
    elif df.loc[i, "age"] >= 56:
        df.loc[i, "age2"] = ">56"

df.drop(columns="age", inplace=True)

df.rename(columns={'age2': 'age'}, inplace=True)

df

,gender,bmi,children,smoker,region,medical_history,family_medical_history,exercise_frequency,occupation,coverage_level,charges,age
1,female,34.61,4,yes,northwest,High blood pressure,Diabetes,Never,Unemployed,Premium,18397.374698,26-41
2,male,42.43,4,no,southeast,High blood pressure,Heart disease,Frequently,White collar,Premium,22269.896850,41-56
5,female,48.72,4,no,northeast,Diabetes,Heart disease,Never,Unemployed,Basic,14848.601422,>56
6,male,20.22,2,yes,southeast,High blood pressure,Diabetes,Frequently,White collar,Basic,17850.551816,26-41
15,female,22.27,1,yes,northwest,High blood pressure,Heart disease,Occasionally,Student,Basic,17650.377560,41-56
...,...,...,...,...,...,...,...,...,...,...,...,...
13322,female,32.84,4,no,northeast,Diabetes,High blood pressure,Never,Blue collar,Standard,12520.033741,26-41
13323,female,34.30,0,no,southwest,Heart disease,High blood pressure,Rarely,White collar,Standard,15849.388822,41-56
13324,male,44.77,0,no,northwest,Heart disease,Diabetes,Rarely,Unemployed,Standard,15854.662913,>56
13326,female,27.70,5,no,southwest,Diabetes,High blood pressure,Rarely,Unemployed,Basic,8500.473542,26-41
13327,male,38.92,4,no,southeast,Heart disease,Heart disease,Occasionally,Blue collar,Basic,19109.652331,18-26

In [22]:

for i in df.index:
    if df.loc[i, "bmi"] < 18.5:
        df.loc[i, "bmi2"] = "< 18.5"
    elif 18.5 <= df.loc[i, "bmi"] < 25:
        df.loc[i, "bmi2"] = "18.5 - 25"
    elif 25 <= df.loc[i, "bmi"] < 30:
        df.loc[i, "bmi2"] = "25 - 30"
    elif 30 <= df.loc[i, "bmi"] < 35:
        df.loc[i, "bmi2"] = "30 - 35"
    elif 35 <= df.loc[i, "bmi"] < 40:
        df.loc[i, "bmi2"] = "35 - 40"
    elif df.loc[i, "bmi"] >= 40:
        df.loc[i, "bmi2"] = "40 - 54"
    

df.drop(columns="bmi", inplace=True)

df.rename(columns={'bmi2': 'bmi'}, inplace=True)

df

,gender,children,smoker,region,medical_history,family_medical_history,exercise_frequency,occupation,coverage_level,charges,age,bmi
1,female,4,yes,northwest,High blood pressure,Diabetes,Never,Unemployed,Premium,18397.374698,26-41,30 - 35
2,male,4,no,southeast,High blood pressure,Heart disease,Frequently,White collar,Premium,22269.896850,41-56,40 - 54
5,female,4,no,northeast,Diabetes,Heart disease,Never,Unemployed,Basic,14848.601422,>56,40 - 54
6,male,2,yes,southeast,High blood pressure,Diabetes,Frequently,White collar,Basic,17850.551816,26-41,18.5 - 25
15,female,1,yes,northwest,High blood pressure,Heart disease,Occasionally,Student,Basic,17650.377560,41-56,18.5 - 25
...,...,...,...,...,...,...,...,...,...,...,...,...
13322,female,4,no,northeast,Diabetes,High blood pressure,Never,Blue collar,Standard,12520.033741,26-41,30 - 35
13323,female,0,no,southwest,Heart disease,High blood pressure,Rarely,White collar,Standard,15849.388822,41-56,30 - 35
13324,male,0,no,northwest,Heart disease,Diabetes,Rarely,Unemployed,Standard,15854.662913,>56,40 - 54
13326,female,5,no,southwest,Diabetes,High blood pressure,Rarely,Unemployed,Basic,8500.473542,26-41,25 - 30
13327,male,4,no,southeast,Heart disease,Heart disease,Occasionally,Blue collar,Basic,19109.652331,18-26,35 - 40

In [26]:
df['gender'] = df['gender'].str.strip()
df['smoker'] = df['smoker'].str.strip()
df['medical_history'] = df['medical_history'].str.strip()
df['family_medical_history'] = df['family_medical_history'].str.strip()
df['exercise_frequency'] = df['exercise_frequency'].str.strip()
df['occupation'] = df['occupation'].str.strip()
df['coverage_level'] = df['coverage_level'].str.strip()

In [ ]:
df.to_csv("./df_cleaned2.csv", sep=",", index=False)